### ISSUE TITLE
1주차 추가 과제 (문제 풀이 ~3/24)

### ISSUE THREAD

**Issue by che2ese** [che2ese/Dongguk_StudyGroup#4]
[1주차 문제.zip](https://github.com/che2ese/Dongguk_StudyGroup/files/14624329/1.zip)

1. 1주차 문제 폴더에서 sin이나 cpp파일 선택해 문제 확인한다.
2. 새로운 프로젝트를 만든다. -> 파일명 : 이름/1주차 과제
    이 때 경로 설정을 잘 해야됨 (바탕화면에 스터디 그룹 폴더 만들어놓으면 좋음)
3. 프로젝트 내에 소스파일을 만들어 이름은 문제 번호로 적는다. 
4. 문제를 복붙해 주석 처리 한다.
5. 1번 문제를 풀었으면 1번 소스파일을 마우스 우클릭해 제거한다. 그 다음 창에서도 제거 (삭제 누르면 안됨)
6. 제거한 후 해당 프로젝트에 2번 소스파일을 만든다.
7. 이 방법으로 10번까지 푼 후 자신의 레포지토리에 프로젝트 파일 전체를 올려 pull request한다.
    pull request 방법은 우리 스터디 레포지토리 README에 상세히 적혀 있음

**Comment by eunji9** [comment]
과제 올라온거 확인했어염
